# DataFrames II: Filtrar Data

In [1]:
import pandas as pd
import os

In [2]:
#ruta del archivo actual
curr_path = os.getcwd()
print(curr_path)

datasets_path = os.path.join(curr_path, "..", "All_Datasets")
print(datasets_path)

c:\Users\MATEOCRACK\Desktop\familia\santi\factultade\proc_limpieza_visualizazcion\teoria
c:\Users\MATEOCRACK\Desktop\familia\santi\factultade\proc_limpieza_visualizazcion\teoria\..\All_Datasets


### Conversión de Fechas y Tiempos 🕒
- El método `pd.to_datetime` convierte una **Series** en valores de tipo datetime.
- El parámetro `format` informa a pandas sobre el formato en que están almacenados los datos de tiempo.
- Usa símbolos para designar los segmentos de la cadena:
  - `%m`: Mes.
  - `%d`: Día.
  - '%p': PM/AM
- El atributo `dt` revela un objeto con múltiples atributos y métodos relacionados con fechas y tiempos.
  - El atributo `dt.time` extrae solo la hora de cada valor en una **Series** datetime.
- Usa el método `astype` para convertir los valores de una **Series** a otro tipo.
- El parámetro `parse_dates` de `read_csv` es otra forma de analizar cadenas como valores datetime.


observaicones: MINUSCULAS cosas de fechas, MAYUSCULAS cosas de tiempo

**Configureaciones del format**:

tiempo
- Y: año compleyo (2026)
- H: HORA 24h
- M: Minuto
- S: segundo
- I = hora 0-12
- p AM/PM

fechas:
- m = month
- d = day
- y = año corto (26)

otros: 
- A: Dia completo
- a: dia abreviado
- B: mes completo
- b: mes abreviado
- j: dia del año


**Tipo de dato datetime**

datetime es un dato de pandas. Representa nanosegundos. COn el podemos guardar los nanosegundos asociadas a una fecha y la veremos como 1993-04-23 00:00:00 pudiendo acceder a:
- fecha.day, fecha.month, fecha.year
- fecha.hour, fecha.minute, fecha.second
- fecha.dayofweek, fecha.weekday, fecha.day_name, fecha.month_name, fecha.dayofyear

unmonton.

In [57]:
employees = pd.read_csv(datasets_path + "/employees.csv", sep = ";", encoding="latin1") #inchequeable
employees

employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    str
 2   Start Date         1000 non-null   str
 3   Last Login Time    1000 non-null   str
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    str
dtypes: float64(1), int64(1), object(1), str(5)
memory usage: 62.6+ KB

In [58]:
display(employees["Start Date"]) #formado dd/mm/yy

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format= "%m/%d/%Y") #format es como viene la fecha!!!!
#pd to datetime la traduce a yyyy mm dd

display(employees)

0        8/6/1993
1       3/31/1996
2       4/23/1993
3        3/4/2005
4       1/24/1998
          ...
995    11/23/2014
996     1/31/1984
997     5/20/2013
998     4/20/2013
999     5/15/2012
Name: Start Date, Length: 1000, dtype: str

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42 p. m.,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,6:53 a. m.,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17 a. m.,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1:00 p. m.,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,4:47 p. m.,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,6:09 a. m.,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,6:30 a. m.,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39 p. m.,96914,1.421,False,Product
998,Larry,Male,2013-04-20,4:45 p. m.,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,6:24 p. m.,129949,10.169,True,Sales

In [59]:
employees["Last Login Time"] = (
    employees["Last Login Time"]
    .str.replace("a. m.", "AM", regex=False)
    .str.replace("p. m.", "PM", regex=False)
    .str.replace("a.\xa0m.", "AM", regex=False)
    .str.replace("p.\xa0m.", "PM", regex=False)
)

In [66]:
display(pd.to_datetime(employees["Last Login Time"], format="%H:%M %p")) #da una serie indice, datetime
display(pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt) #ni idea

display(pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time) #ni idea

0     1900-01-01 12:42:00
1     1900-01-01 06:53:00
2     1900-01-01 11:17:00
3     1900-01-01 01:00:00
4     1900-01-01 04:47:00
              ...
995   1900-01-01 06:09:00
996   1900-01-01 06:30:00
997   1900-01-01 12:39:00
998   1900-01-01 04:45:00
999   1900-01-01 06:24:00
Name: Last Login Time, Length: 1000, dtype: datetime64[us]

0      12:42:00
1      06:53:00
2      11:17:00
3      01:00:00
4      04:47:00
         ...
995    06:09:00
996    06:30:00
997    12:39:00
998    04:45:00
999    06:24:00
Name: Last Login Time, Length: 1000, dtype: object

In [ ]:
#hora y tiempo tambien es un string, pasemolos a datetime. EL dato viene en formato %h,M, PM
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p")
display(employees) #se tuvo que inventar una fecha para poder crear el tipo de dato. Pero nos podemos quedar solo con el tipo de datos time


employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,1900-01-01 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,1900-01-01 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,1900-01-01 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1900-01-01 01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,1900-01-01 04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,1900-01-01 06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,1900-01-01 06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,1900-01-01 12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,1900-01-01 04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,1900-01-01 06:24:00,129949,10.169,True,Sales

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [49]:
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,1900-01-01 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,1900-01-01 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,1900-01-01 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1900-01-01 01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,1900-01-01 04:47:00,101004,1.389,True,Client Services

In [ ]:
#Hora y tiempo - Hora:Minutos pm/am
#dt = date time
#time extracted with .time
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time

In [ ]:
#Conversion a booleano
employees["Senior Management"] = employees["Senior Management"].astype(bool)

In [ ]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 55.8+ KB

In [ ]:
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [ ]:
#Conversion a categoria
employees["Gender"] = employees["Gender"].astype("category")

In [ ]:
#Revision de memoria usada
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 49.1+ KB

In [ ]:
employees = pd.read_csv(path + "employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")

In [ ]:
#Resumen de conversion de datos
employees = pd.read_csv(path+"employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

## Filtrar un DataFrame Basado en una Condición 🧐
- Pandas necesita una **Series** de valores booleanos (`True`/`False`) para realizar un filtro.
- Pasa la **Series** booleana dentro de corchetes después del **DataFrame**.
- Una **Series** booleana puede generarse usando una variedad de operaciones:
  - Igualdad, desigualdad, menor que, mayor que, inclusión, etc.

In [ ]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
#Podemos agregar tiempos
import datetime as dt

In [ ]:
employees["Gender"] == "Male"

0       True
1       True
2      False
3       True
4       True
       ...
995    False
996     True
997     True
998     True
999     True
Name: Gender, Length: 1000, dtype: bool

In [ ]:
employees[employees["Gender"] == "Male"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [ ]:
filtro_finanzas = employees["Team"] == "Finance"

In [ ]:
test_employees = employees[filtro_finanzas]

In [ ]:
test_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,07:13:00,41426,14.543,True,Finance
46,Bruce,Male,2009-11-28,10:47:00,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,1998-07-27,11:12:00,137144,10.081,False,Finance
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [ ]:
#Pruebas booleanas, ponemos nuestro dataframe[dataframe[columna] == valor] para realizar el test

employees[employees["Gender"] == "Male"]

employees[employees["Team"] == "Finance"]

on_finance_team = employees["Team"] == "Finance"

employees[on_finance_team]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,07:13:00,41426,14.543,True,Finance
46,Bruce,Male,2009-11-28,10:47:00,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,1998-07-27,11:12:00,137144,10.081,False,Finance
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [ ]:
#Empelados que ganan mas de 1000000
filtro_salario_millon = employees["Salary"] > 100000
employees[filtro_salario_millon]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [ ]:
employees[employees["Start Date"] < "1985-01-01"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
28,Terry,Male,1981-11-27,06:30:00,124008,13.464,True,Client Services
37,Linda,Female,1981-10-19,08:49:00,57427,9.557,True,Client Services
...,...,...,...,...,...,...,...,...
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [ ]:
employees[employees["Senior Management"]].head()

employees[employees["Salary"] > 110000]

employees[employees["Bonus %"] < 1.5]

employees[employees["Start Date"] < "1985-01-01"]

employees[employees["Last Login Time"] < dt.time(12, 0, 0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

## Filtrar con Más de Una Condición (AND) 🔗
- Usa el operador `&` entre dos **Series** booleanas para filtrar por múltiples condiciones.
- Asigna las **Series** a variables para hacer el código más legible.

In [ ]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")

employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time

employees["Senior Management"] = employees["Senior Management"].astype(bool)

employees["Gender"] = employees["Gender"].astype("category")

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
# Empleadas mujeres que trabajan en marketing y que ganan mas de 100k al año
is_female = employees["Gender"] == "Female"
is_in_marketing = employees["Team"] == "Marketing"
salary_over_100k = employees["Salary"] > 100000

In [ ]:
is_female & is_in_marketing & salary_over_100k

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
#Conjunto de booleanos
is_female & is_in_marketing & salary_over_100k

# True, True -> True
# True, False -> False
# False, True -> False
# False, False -> False

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
employees[is_female & is_in_marketing & salary_over_100k]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
468,Janice,Female,1997-06-28,01:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,01:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,09:10:00,123649,10.154,True,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
656,Lisa,Female,1982-02-09,06:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,06:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
881,Ruby,Female,1980-01-28,11:08:00,142868,6.318,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

## Filtrar con Más de Una Condición (OR) 🔄
- Usa el operador `|` entre dos **Series** booleanas para filtrar por *cualquiera* de las condiciones.

In [ ]:
employees = pd.read_csv(path + "employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
is_senior_management = employees["Senior Management"]
is_senior_management

0       True
1       True
2      False
3       True
4       True
       ...
995    False
996    False
997    False
998    False
999     True
Name: Senior Management, Length: 1000, dtype: bool

In [ ]:
is_senior_management = employees["Senior Management"]
started_in_80s = employees["Start Date"] < "1990-01-01"

employees[is_senior_management | started_in_80s]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [ ]:
# Ejemplo de OR:
# True + True -> True
# T + F -> T
# F + T -> T
# T + F -> T
# F + F -> F

In [ ]:
# Si quiero obtener el nombre de un empleado que el primer nombre es "Robert" que trabaja en "Client Services" O empleados que empezaron a trabajar desde el "2016-06-01"

In [ ]:
#Pruebas booleanas
is_robert = employees["First Name"] == "Robert"
is_in_client_services = employees["Team"] == "Client Services"
start_date_after_june_2016 = employees["Start Date"] > "2016-06-01"

In [ ]:
employees[ (is_robert & is_in_client_services) | start_date_after_june_2016 ]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services
451,Terry,NaN,2016-07-15,12:29:00,140002,19.490,True,Marketing

## El Método `isin` ✅
- El método `isin` de una **Series** acepta un objeto de colección como una lista, tupla o **Series**.
- Devuelve `True` para una fila si su valor se encuentra en la colección.

In [ ]:
employees = pd.read_csv(path+"employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
legal_team = employees["Team"] == "Legal"
sales_team = employees["Team"] == "Sales"
product_team = employees["Team"] == "Product"

employees[legal_team | sales_team | product_team]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [ ]:
#Ejemplo con el isin()
target_teams = employees["Team"].isin(["Legal", "Sales","Product"])
employees[target_teams]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

## Métodos `isnull` y `notnull` 🔍
- El método `isnull` devuelve `True` para los valores `NaN` en una **Series**.
- El método `notnull` devuelve `True` para los valores presentes en una **Series**.

In [ ]:
employees = pd.read_csv(path+"employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
employees.isnull().sum()

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management      0
Team                  43
dtype: int64

In [ ]:
employees[employees["Team"].isnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
23,NaN,Male,2012-06-14,04:19:00,125792,5.042,True,NaN
32,NaN,Male,1998-08-21,02:27:00,122340,6.417,True,NaN
91,James,NaN,2005-01-26,11:00:00,128771,8.309,False,NaN
109,Christopher,Male,2000-04-22,10:15:00,37919,11.449,False,NaN
139,NaN,Female,1990-10-03,01:08:00,132373,10.527,True,NaN
199,Jonathan,Male,2009-07-17,08:15:00,130581,16.736,True,NaN
258,Michael,Male,2002-01-24,03:04:00,43586,12.659,False,NaN
290,Jeremy,Male,1988-06-14,06:20:00,129460,13.657,True,NaN
314,Bobby,Male,1996-03-31,05:40:00,112117,6.338,False,NaN
367,Edward,Male,1989-08-04,06:06:00,66067,10.957,True,NaN
382,NaN,Female,1996-04-18,03:57:00,107024,12.182,True,NaN
434,Joyce,Female,1995-02-07,07:38:00,50701,14.227,True,NaN
438,Jason,Male,1998-11-20,02:54:00,69244,6.220,True,NaN
445,Chris,Male,2006-12-12,01:57:00,71642,1.496,False,NaN
479,Richard,Male,1997-07-04,11:47:00,47647,18.787,True,NaN
512,Wanda,Female,1993-04-06,03:11:00,78883,19.695,False,NaN
513,Jimmy,Male,2013-11-19,07:29:00,63549,19.624,False,NaN
520,Peter,Male,2003-02-22,09:09:00,56580,8.411,True,NaN
567,NaN,Female,1980-04-01,08:04:00,48141,12.605,True,NaN
573,Kimberly,Female,1981-12-30,04:51:00,81800,5.435,True,NaN
580,Harry,Male,1985-01-27,08:18:00,65482,18.089,False,NaN
626,NaN,Female,1997-04-13,08:03:00,131755,2.930,True,NaN
634,Carl,Male,1987-03-30,05:59:00,75598,19.289,False,NaN
635,Randy,Male,2000-09-27,03:04:00,89831,13.047,True,NaN
647,Donald,Male,1988-04-06,10:00:00,122920,5.320,False,NaN
669,Joseph,NaN,1982-03-28,01:05:00,86564,11.879,True,NaN
684,Alice,Female,2016-01-21,05:07:00,117787,10.485,False,NaN
706,Todd,Male,1993-07-04,06:53:00,128175,18.473,True,NaN
726,Daniel,Male,2016-02-29,04:04:00,77287,13.000,True,NaN
753,Antonio,Male,1999-06-06,10:54:00,41928,5.478,True,NaN
774,NaN,Female,2000-06-18,07:36:00,106428,10.867,True,NaN
781,Lawrence,Male,1995-07-03,10:55:00,46378,9.127,False,NaN
794,Nicole,Female,2004-03-01,05:17:00,44021,10.286,False,NaN
826,NaN,NaN,1988-08-01,01:35:00,87103,5.665,True,NaN
850,Charles,Male,1997-09-03,10:04:00,148291,6.002,False,NaN
851,Bobby,Male,1996-08-19,01:16:00,147842,16.158,True,NaN
853,Mildred,Female,2007-04-06,10:06:00,139284,11.390,True,NaN
855,Phillip,NaN,2003-10-20,11:09:00,89700,2.277,True,NaN
864,Ryan,Male,2012-11-16,01:47:00,57292,6.010,False,NaN
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN

In [ ]:
employees[employees["First Name"].isnull() & employees["Team"].notnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
25,NaN,Male,2012-10-08,01:12:00,37076,18.576,True,Client Services
39,NaN,Male,2016-01-29,02:33:00,122173,7.797,True,Client Services
51,NaN,NaN,2011-12-17,08:29:00,41126,14.009,True,Sales
62,NaN,Female,2007-06-12,05:25:00,58112,19.414,True,Marketing
116,NaN,Male,1991-06-22,08:58:00,76189,18.988,True,Legal
149,NaN,Female,2014-08-17,02:00:00,86230,8.578,True,Distribution
157,NaN,Female,2005-07-27,08:32:00,79536,14.443,True,Product
165,NaN,Female,2014-03-23,01:28:00,59148,9.061,True,Legal
166,NaN,Female,1991-07-09,06:52:00,42341,7.014,True,Sales
174,NaN,NaN,2007-09-18,06:59:00,40297,6.185,True,Client Services
186,NaN,Female,2005-02-23,09:50:00,149654,1.825,True,Sales
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
253,NaN,NaN,2003-04-28,03:01:00,113732,10.391,True,Sales
257,NaN,Male,1999-11-25,06:16:00,42676,15.517,True,Sales
266,NaN,Female,2009-08-05,08:14:00,115145,14.063,True,Distribution
267,NaN,Male,2005-02-04,01:01:00,40451,16.044,True,Distribution
269,NaN,Female,1992-08-02,08:35:00,145316,18.517,True,Human Resources
320,NaN,Female,2008-07-08,11:40:00,62960,14.356,True,Sales
329,NaN,Male,2010-01-27,02:57:00,87760,14.987,True,Engineering
352,NaN,Male,2011-10-09,09:29:00,69906,4.844,True,Engineering
353,NaN,Male,1997-04-22,09:36:00,65078,3.095,True,Marketing
374,NaN,Female,2006-12-31,11:02:00,81444,3.171,True,Distribution
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
416,NaN,Male,2008-06-29,05:23:00,111043,5.966,True,Distribution
444,NaN,Male,2016-05-24,09:17:00,76409,7.008,True,Distribution
454,NaN,Male,1995-02-21,12:26:00,136602,10.429,True,Marketing
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
483,NaN,Female,1992-04-26,08:01:00,115436,3.099,True,Human Resources
504,NaN,Female,2014-06-24,10:05:00,38275,10.494,True,Distribution
505,NaN,Male,1980-04-20,01:17:00,71520,13.248,True,Engineering
521,NaN,NaN,1981-09-25,09:59:00,83895,17.971,True,Engineering
540,NaN,Female,2009-12-02,03:30:00,84746,4.820,True,Finance
574,NaN,Female,2009-01-13,01:01:00,118736,7.421,True,Client Services
599,NaN,Female,1990-10-11,10:57:00,98385,10.925,True,Human Resources
607,NaN,Male,1983-10-13,11:59:00,139754,12.740,True,Sales
608,NaN,Female,1993-10-24,05:17:00,116236,17.274,True,Engineering
628,NaN,NaN,1988-09-02,12:49:00,147309,1.702,True,Distribution
674,NaN,Male,2012-08-28,07:56:00,88733,1.932,True,Human Resources
685,NaN,Male,1989-10-20,09:37:00,88086,19.387,True,Finance
687,NaN,Male,1996-12-27,07:07:00,139959,8.992,True,Distribution
697,NaN,Male,1990-05-23,02:09:00,136655,9.801,True,Distribution
709,NaN,Male,1995-04-07,04:32:00,60411,12.048,True,Human Resources
733,NaN,Male,2009-06-17,01:00:00,136681,3.655,True,Business Development
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
773,NaN,Male,1986-10-24,09:23:00,47176,10.736,True,Finance
782,NaN,Male,1986-05-06,04:41:00,74104,17.680,True,Client Services
783,NaN,NaN,1991-04-15,03:39:00,132505,13.592,True,Product
785,NaN,Female,1982-07-24,12:00:00,57811,8.941,True,Marketing
812,NaN,Male,1994-12-13,10:34:00,141311,5.478,True,Product
821,NaN,Female,1980-12-27,02:27:00,80399,12.254,True,Distribution
823,NaN,Male,2009-11-12,02:30:00,109411,9.494,True,Engineering
877,NaN,Male,1980-09-05,07:36:00,114896,13.823,True,Client Services
890,NaN,Male,2015-11-24,03:11:00,145329,7.100,True,Finance
902,NaN,Male,2001-05-23,07:52:00,103877,6.322,True,Distribution
925,NaN,Female,2000-08-23,04:19:00,95866,19.388,True,Sales
946,NaN,Female,1985-09-15,01:50:00,133472,16.941,True,Distribution
947,NaN,Male,2012-07-30,03:07:00,107351,5.329,True,Marketing

In [ ]:
employees[employees["Team"].isnull()]

employees[employees["Team"].notnull()]

employees[employees["First Name"].isnull() & employees["Team"].notnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
25,NaN,Male,2012-10-08,01:12:00,37076,18.576,True,Client Services
39,NaN,Male,2016-01-29,02:33:00,122173,7.797,True,Client Services
51,NaN,NaN,2011-12-17,08:29:00,41126,14.009,True,Sales
62,NaN,Female,2007-06-12,05:25:00,58112,19.414,True,Marketing
116,NaN,Male,1991-06-22,08:58:00,76189,18.988,True,Legal
149,NaN,Female,2014-08-17,02:00:00,86230,8.578,True,Distribution
157,NaN,Female,2005-07-27,08:32:00,79536,14.443,True,Product
165,NaN,Female,2014-03-23,01:28:00,59148,9.061,True,Legal
166,NaN,Female,1991-07-09,06:52:00,42341,7.014,True,Sales
174,NaN,NaN,2007-09-18,06:59:00,40297,6.185,True,Client Services
186,NaN,Female,2005-02-23,09:50:00,149654,1.825,True,Sales
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
253,NaN,NaN,2003-04-28,03:01:00,113732,10.391,True,Sales
257,NaN,Male,1999-11-25,06:16:00,42676,15.517,True,Sales
266,NaN,Female,2009-08-05,08:14:00,115145,14.063,True,Distribution
267,NaN,Male,2005-02-04,01:01:00,40451,16.044,True,Distribution
269,NaN,Female,1992-08-02,08:35:00,145316,18.517,True,Human Resources
320,NaN,Female,2008-07-08,11:40:00,62960,14.356,True,Sales
329,NaN,Male,2010-01-27,02:57:00,87760,14.987,True,Engineering
352,NaN,Male,2011-10-09,09:29:00,69906,4.844,True,Engineering
353,NaN,Male,1997-04-22,09:36:00,65078,3.095,True,Marketing
374,NaN,Female,2006-12-31,11:02:00,81444,3.171,True,Distribution
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
416,NaN,Male,2008-06-29,05:23:00,111043,5.966,True,Distribution
444,NaN,Male,2016-05-24,09:17:00,76409,7.008,True,Distribution
454,NaN,Male,1995-02-21,12:26:00,136602,10.429,True,Marketing
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
483,NaN,Female,1992-04-26,08:01:00,115436,3.099,True,Human Resources
504,NaN,Female,2014-06-24,10:05:00,38275,10.494,True,Distribution
505,NaN,Male,1980-04-20,01:17:00,71520,13.248,True,Engineering
521,NaN,NaN,1981-09-25,09:59:00,83895,17.971,True,Engineering
540,NaN,Female,2009-12-02,03:30:00,84746,4.820,True,Finance
574,NaN,Female,2009-01-13,01:01:00,118736,7.421,True,Client Services
599,NaN,Female,1990-10-11,10:57:00,98385,10.925,True,Human Resources
607,NaN,Male,1983-10-13,11:59:00,139754,12.740,True,Sales
608,NaN,Female,1993-10-24,05:17:00,116236,17.274,True,Engineering
628,NaN,NaN,1988-09-02,12:49:00,147309,1.702,True,Distribution
674,NaN,Male,2012-08-28,07:56:00,88733,1.932,True,Human Resources
685,NaN,Male,1989-10-20,09:37:00,88086,19.387,True,Finance
687,NaN,Male,1996-12-27,07:07:00,139959,8.992,True,Distribution
697,NaN,Male,1990-05-23,02:09:00,136655,9.801,True,Distribution
709,NaN,Male,1995-04-07,04:32:00,60411,12.048,True,Human Resources
733,NaN,Male,2009-06-17,01:00:00,136681,3.655,True,Business Development
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
773,NaN,Male,1986-10-24,09:23:00,47176,10.736,True,Finance
782,NaN,Male,1986-05-06,04:41:00,74104,17.680,True,Client Services
783,NaN,NaN,1991-04-15,03:39:00,132505,13.592,True,Product
785,NaN,Female,1982-07-24,12:00:00,57811,8.941,True,Marketing
812,NaN,Male,1994-12-13,10:34:00,141311,5.478,True,Product
821,NaN,Female,1980-12-27,02:27:00,80399,12.254,True,Distribution
823,NaN,Male,2009-11-12,02:30:00,109411,9.494,True,Engineering
877,NaN,Male,1980-09-05,07:36:00,114896,13.823,True,Client Services
890,NaN,Male,2015-11-24,03:11:00,145329,7.100,True,Finance
902,NaN,Male,2001-05-23,07:52:00,103877,6.322,True,Distribution
925,NaN,Female,2000-08-23,04:19:00,95866,19.388,True,Sales
946,NaN,Female,1985-09-15,01:50:00,133472,16.941,True,Distribution
947,NaN,Male,2012-07-30,03:07:00,107351,5.329,True,Marketing

## El Método `between` 🔢
- El método `between` devuelve `True` si un valor de la **Series** se encuentra dentro de un rango definido.

In [ ]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
import datetime as dt

In [ ]:
employees[employees["Team"].isnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
23,NaN,Male,2012-06-14,04:19:00,125792,5.042,True,NaN
32,NaN,Male,1998-08-21,02:27:00,122340,6.417,True,NaN
91,James,NaN,2005-01-26,11:00:00,128771,8.309,False,NaN
109,Christopher,Male,2000-04-22,10:15:00,37919,11.449,False,NaN
139,NaN,Female,1990-10-03,01:08:00,132373,10.527,True,NaN
199,Jonathan,Male,2009-07-17,08:15:00,130581,16.736,True,NaN
258,Michael,Male,2002-01-24,03:04:00,43586,12.659,False,NaN
290,Jeremy,Male,1988-06-14,06:20:00,129460,13.657,True,NaN
314,Bobby,Male,1996-03-31,05:40:00,112117,6.338,False,NaN
367,Edward,Male,1989-08-04,06:06:00,66067,10.957,True,NaN
382,NaN,Female,1996-04-18,03:57:00,107024,12.182,True,NaN
434,Joyce,Female,1995-02-07,07:38:00,50701,14.227,True,NaN
438,Jason,Male,1998-11-20,02:54:00,69244,6.220,True,NaN
445,Chris,Male,2006-12-12,01:57:00,71642,1.496,False,NaN
479,Richard,Male,1997-07-04,11:47:00,47647,18.787,True,NaN
512,Wanda,Female,1993-04-06,03:11:00,78883,19.695,False,NaN
513,Jimmy,Male,2013-11-19,07:29:00,63549,19.624,False,NaN
520,Peter,Male,2003-02-22,09:09:00,56580,8.411,True,NaN
567,NaN,Female,1980-04-01,08:04:00,48141,12.605,True,NaN
573,Kimberly,Female,1981-12-30,04:51:00,81800,5.435,True,NaN
580,Harry,Male,1985-01-27,08:18:00,65482,18.089,False,NaN
626,NaN,Female,1997-04-13,08:03:00,131755,2.930,True,NaN
634,Carl,Male,1987-03-30,05:59:00,75598,19.289,False,NaN
635,Randy,Male,2000-09-27,03:04:00,89831,13.047,True,NaN
647,Donald,Male,1988-04-06,10:00:00,122920,5.320,False,NaN
669,Joseph,NaN,1982-03-28,01:05:00,86564,11.879,True,NaN
684,Alice,Female,2016-01-21,05:07:00,117787,10.485,False,NaN
706,Todd,Male,1993-07-04,06:53:00,128175,18.473,True,NaN
726,Daniel,Male,2016-02-29,04:04:00,77287,13.000,True,NaN
753,Antonio,Male,1999-06-06,10:54:00,41928,5.478,True,NaN
774,NaN,Female,2000-06-18,07:36:00,106428,10.867,True,NaN
781,Lawrence,Male,1995-07-03,10:55:00,46378,9.127,False,NaN
794,Nicole,Female,2004-03-01,05:17:00,44021,10.286,False,NaN
826,NaN,NaN,1988-08-01,01:35:00,87103,5.665,True,NaN
850,Charles,Male,1997-09-03,10:04:00,148291,6.002,False,NaN
851,Bobby,Male,1996-08-19,01:16:00,147842,16.158,True,NaN
853,Mildred,Female,2007-04-06,10:06:00,139284,11.390,True,NaN
855,Phillip,NaN,2003-10-20,11:09:00,89700,2.277,True,NaN
864,Ryan,Male,2012-11-16,01:47:00,57292,6.010,False,NaN
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN

In [ ]:
employees[employees["Salary"].between(60000, 70000)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
41,Christine,NaN,2015-06-28,01:08:00,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
965,Catherine,Female,1989-09-25,01:31:00,68164,18.393,False,Client Services
970,Alice,Female,1988-09-03,08:54:00,63571,15.397,True,Product
974,Harry,Male,2011-08-30,06:31:00,67656,16.455,True,Client Services
978,Sean,Male,1983-01-17,02:23:00,66146,11.178,False,Human Resources
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development

In [ ]:
employees[employees["Salary"].between(60000, 70000)]

employees[employees["Bonus %"].between(2.0, 5.0)]

employees[employees["Start Date"].between("1991-01-01", "1992-01-01")]

employees[employees["Last Login Time"].between(dt.time(8, 30), dt.time(12, 0))]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
...,...,...,...,...,...,...,...,...
977,Sarah,Female,1995-12-04,09:16:00,124566,5.949,False,Product
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance

## El Método `duplicated` 🔁
- El método `duplicated` devuelve `True` si un valor de la **Series** es un duplicado.
- Marca una ocurrencia de un valor repetido como "no duplicado".
- Usa el parámetro `keep` para designar si la primera o última ocurrencia debe considerarse "no duplicada".
- Pasa `False` al parámetro `keep` para marcar todas las ocurrencias de valores repetidos como duplicados.
- Usa el símbolo tilde (`~`) para invertir los valores de una **Series**: `True` se convierte en `False` y viceversa.

In [ ]:
employees = pd.read_csv(path+"employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
employees["First Name"].duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996     True
997     True
998     True
999     True
Name: First Name, Length: 1000, dtype: bool

In [ ]:
#Primero lee douglas, lo que va a devolver un falso, luego los proximos douglas devolvera un true
employees[employees["First Name"].duplicated()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
23,NaN,Male,2012-06-14,04:19:00,125792,5.042,True,NaN
25,NaN,Male,2012-10-08,01:12:00,37076,18.576,True,Client Services
32,NaN,Male,1998-08-21,02:27:00,122340,6.417,True,NaN
34,Jerry,Male,2004-01-10,12:56:00,95734,19.096,False,Client Services
39,NaN,Male,2016-01-29,02:33:00,122173,7.797,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [ ]:
employees[employees["First Name"].duplicated(keep="last")]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
959,Albert,Male,1992-09-19,02:35:00,45094,5.850,True,Business Development
960,Stephen,Male,1989-10-29,11:34:00,93997,18.093,True,Business Development
970,Alice,Female,1988-09-03,08:54:00,63571,15.397,True,Product
973,Russell,Male,2013-05-10,11:08:00,137359,11.105,False,Business Development
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources

In [ ]:
employees[employees["First Name"].duplicated()]

#Cual consideramos? El primero o el ultimo?
employees[employees["First Name"].duplicated(keep="first")]

employees[employees["First Name"].duplicated(keep="last")]

employees[employees["First Name"].duplicated(keep=False)]

employees[~employees["First Name"].duplicated(keep=False)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,10:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,03:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal

In [ ]:
employees["Gender"]

0        Male
1        Male
2      Female
3        Male
4        Male
        ...
995       NaN
996      Male
997      Male
998      Male
999      Male
Name: Gender, Length: 1000, dtype: object

In [ ]:
employees["Gender"].duplicated()

0      False
1       True
2      False
3       True
4       True
       ...
995     True
996     True
997     True
998     True
999     True
Name: Gender, Length: 1000, dtype: bool

## El Método `drop_duplicates` 🗑️
- El método `drop_duplicates` elimina filas con valores duplicados.
- Por defecto, elimina una fila si *todos* sus valores se comparten con otra fila.
- El parámetro `subset` configura las columnas donde buscar valores duplicados.
- Pasa una lista al parámetro `subset` para buscar duplicados en múltiples columnas.

In [ ]:
employees = pd.read_csv(path +"employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
employees.drop_duplicates("Team")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution

In [ ]:
employees.drop_duplicates()

employees.drop_duplicates("Team")
employees.drop_duplicates("Team", keep="first")
employees.drop_duplicates("Team", keep="last")
employees.drop_duplicates("Team", keep=False)

employees.drop_duplicates("First Name", keep=False)

employees.drop_duplicates(["Senior Management", "Team"]).sort_values("Team")

employees.drop_duplicates(["Senior Management", "Team"], keep="last").sort_values("Team")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
971,Patrick,Male,2002-12-30,02:01:00,75423,5.368,True,Business Development
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
965,Catherine,Female,1989-09-25,01:31:00,68164,18.393,False,Client Services
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
946,NaN,Female,1985-09-15,01:50:00,133472,16.941,True,Distribution
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
984,Maria,Female,2011-10-15,04:53:00,43455,13.040,False,Engineering
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
976,Denise,Female,1992-10-19,05:42:00,137954,4.195,True,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
979,Ernest,Male,2013-07-20,06:41:00,142935,13.198,True,Product
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
975,Susan,Female,1995-04-07,10:05:00,92436,12.467,False,Sales
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN

## Métodos `unique` y `nunique` 🎯
- El método `unique` en una **Series** devuelve una colección de sus valores únicos (no disponible en un **DataFrame**).
- El método `nunique` devuelve un conteo de los valores únicos en la **Series** o **DataFrame**.
- El parámetro `dropna` configura si incluir o excluir valores faltantes (`NaN`).

In [ ]:
employees = pd.read_csv(path+"employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
employees["Gender"].unique()

['Male', 'Female', NaN]
Categories (2, object): ['Female', 'Male']

In [ ]:
employees["Gender"].nunique()

2

In [ ]:
employees["Gender"].unique()
type(employees["Gender"].unique())

employees["Team"].unique()
type(employees["Team"].unique())

11

In [ ]:
employees["Team"].unique()

array(['Marketing', nan, 'Finance', 'Client Services', 'Legal', 'Product',
       'Engineering', 'Business Development', 'Human Resources', 'Sales',
       'Distribution'], dtype=object)

In [ ]:
employees["Team"].nunique()
employees["Team"].nunique(dropna=True)
employees["Team"].nunique(dropna=False)

11

In [ ]:
employees["Team"].nunique()

10

In [ ]:
employees["Senior Management"].unique()

array([ True, False])

In [ ]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 49.1+ KB