# DataFrames III: Extraccion

In [ ]:
#Importamos la libreria pandas
import pandas as pd

## Conjunto de Datos de Este Módulo 🎬
- El conjunto de datos de este módulo es una colección de todas las películas de James Bond.

In [ ]:
bond = pd.read_csv("jamesbond.csv", sep = ";")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

## Métodos `set_index` y `reset_index` 🔄
- El índice actúa como la colección de identificadores primarios/etiquetas/puntos de entrada para las filas.
- Extraer una fila desde un índice ordenado por posición o etiqueta es el método más rápido.
- Pandas utiliza las etiquetas/valores de índice al fusionar diferentes objetos.
- El método `set_index` establece una columna existente como índice del **DataFrame**.
- El método `reset_index` restablece el índice estándar numérico ascendente como índice del **DataFrame**.

In [ ]:
bond = pd.read_csv("jamesbond.csv", sep = ";")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [ ]:
bond = bond.set_index("Film")
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [ ]:
bond = bond.reset_index()
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [ ]:
bond = bond.reset_index().set_index("Year")

In [ ]:
bond = bond.set_index("Year")

In [ ]:
bond.head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

## Recuperar Filas por Posición de Índice con `iloc` 🎯
- El accesor `iloc` recupera una o más filas por posición de índice.
- Usa un par de corchetes después del accesor.
- `iloc` acepta valores individuales, listas y slices.

In [ ]:
bond = pd.read_csv("jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [ ]:
bond.iloc[5]
bond.iloc[[15, 20]]
bond.iloc[4:8]
bond.iloc[0:6]
bond.iloc[:6]
bond.iloc[20:] #Slicing -> traer paerte de la informacion

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

## Recuperar Filas por Etiqueta de Índice con `loc` 🔖
- El accesor `loc` recupera una o más filas por etiqueta de índice.
- Usa un par de corchetes después del accesor.

In [ ]:
bond = pd.read_csv("jamesbond.csv", sep = ";", index_col="Film")
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [ ]:
bond.loc["Goldfinger"]

Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: Goldfinger, dtype: object

In [ ]:
bond.loc["Dr. No"] # Etiqueta

Year                          1962
Actor                 Sean Connery
Director             Terence Young
Box Office                   448.8
Budget                         7.0
Bond Actor Salary              0.6
Name: Dr. No, dtype: object

In [ ]:
bond.iloc[0] # Posicion!

Year                          1962
Actor                 Sean Connery
Director             Terence Young
Box Office                   448.8
Budget                         7.0
Bond Actor Salary              0.6
Name: Dr. No, dtype: object

In [ ]:
bond.loc["Goldfinger"]
bond.loc["GoldenEye"]
bond.loc["Casino Royale"]
# bond.loc["Sacred Bond"]

bond.loc[["Octopussy", "Moonraker"]]
bond.loc[["Moonraker", "Octopussy"]]
bond.loc[["Moonraker", "Octopussy", "Casino Royale"]]
# bond.loc[["Moonraker", "Octopussy", "Casino Royale", "Gold Bond"]]

bond.loc["Diamonds Are Forever":"Moonraker"]
bond.loc["Moonraker":"Diamonds Are Forever"]

bond.loc["GoldenEye":] #Del registro Golden Eye hasta el final
bond.loc[:"On Her Majesty's Secret Service"] #Todos los reg del principio hasta "On her ..."


#Errores con un indice que no es unico!

# bond.loc[:"Casino Royale"]
# bond.loc["Casino Royale":]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

## Segundo Argumento en los Accesores `loc` e `iloc` ➕
- El segundo valor dentro de los corchetes apunta a las columnas.
- `iloc` requiere posiciones numéricas para las filas y columnas.
- `loc` requiere etiquetas para las filas y columnas.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film",sep=";").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
bond.loc["Diamonds Are Forever", "Director"] # [Valor del Indice (etiqueta), Columna deseada]

'Guy Hamilton'

In [ ]:
#Pasamos directamente la columna como 2 argumento
bond.loc["Diamonds Are Forever", "Director"]
bond.loc[["Octopussy", "GoldenEye"], "Director"]
bond.loc[["Octopussy", "GoldenEye"], "Director":"Budget"]
bond.loc["GoldenEye":"Octopussy", "Director":"Budget"]
bond.loc["GoldenEye":"Octopussy", ["Actor", "Bond Actor Salary", "Year"]]

                                Actor  Bond Actor Salary  Year
Film
GoldenEye              Pierce Brosnan                5.1  1995
Goldfinger               Sean Connery                3.2  1964
Licence to Kill        Timothy Dalton                7.9  1989
Live and Let Die          Roger Moore                NaN  1973
Moonraker                 Roger Moore                NaN  1979
Never Say Never Again    Sean Connery                NaN  1983
No Time to Die           Daniel Craig               25.0  2021
Octopussy                 Roger Moore                7.8  1983

In [ ]:
bond.head(1)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [ ]:
bond.iloc[0, 2]

'John Glen'

In [ ]:
bond.iloc[0, 2]
bond.iloc[3, 5]
bond.iloc[[0, 2], 3]
bond.iloc[[0, 2], [3, 5]]
bond.iloc[:7, :3]

                      Year           Actor         Director
Film
A View to a Kill      1985     Roger Moore        John Glen
Casino Royale         2006    Daniel Craig  Martin Campbell
Casino Royale         1967     David Niven       Ken Hughes
Diamonds Are Forever  1971    Sean Connery     Guy Hamilton
Die Another Day       2002  Pierce Brosnan     Lee Tamahori
Dr. No                1962    Sean Connery    Terence Young
For Your Eyes Only    1981     Roger Moore        John Glen

## Sobrescribir un Valor en un DataFrame ✏️
- Usa los accesorios `iloc` o `loc` en el **DataFrame** para apuntar a un valor y asigna uno nuevo con el signo igual.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film", sep = ";").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
#Duplicar el salario de "a view to a kill"
bond.loc["A View to a Kill","Bond Actor Salary"] = bond.loc["A View to a Kill","Bond Actor Salary"] * 2

NameError: name 'bond' is not defined

'Sean Connery'

In [ ]:
#Conversion de Sean a Caballero
bond.loc["Diamonds Are Forever", "Actor"]
bond.loc["Diamonds Are Forever", "Actor"] = "Sir Sean Connery"

In [ ]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Sobrescribir Múltiples Valores en un DataFrame ✏️✏️
- El método `replace` reemplaza todas las ocurrencias de un valor en una **Series**.
- Para sobrescribir múltiples valores en un **DataFrame**, usa los accesorios `loc` o `iloc`.
- Estos accesorios pueden aceptar **Series** booleanas para apuntar a los valores específicos a sobrescribir.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
bond["Actor"] = bond["Actor"].replace("Sean Connery", "Sir Sean Connery") # (Valor que vamos a reemplazar, Valor nuevo)

In [ ]:
bond["Actor"] == "Sean Connery"

Film
A View to a Kill                   False
Casino Royale                      False
Casino Royale                      False
Diamonds Are Forever               False
Die Another Day                    False
Dr. No                             False
For Your Eyes Only                 False
From Russia with Love              False
GoldenEye                          False
Goldfinger                         False
Licence to Kill                    False
Live and Let Die                   False
Moonraker                          False
Never Say Never Again              False
No Time to Die                     False
Octopussy                          False
On Her Majesty's Secret Service    False
Quantum of Solace                  False
Skyfall                            False
Spectre                            False
The Living Daylights               False
The Man with the Golden Gun        False
The Spy Who Loved Me               False
The World Is Not Enough            False
Thunderball                        False
Tomorrow Never Dies                False
You Only Live Twice                False
Name: Actor, dtype: bool

In [ ]:
bond[bond["Actor"] == "Sean Connery"].loc[:, "Actor"] = "Sir Sean Connery"

In [ ]:
is_sean_connery = bond["Actor"] == "Sean Connery"
bond.loc[is_sean_connery, "Actor"] = "Sir Sean Connery"

In [ ]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Renombrar Etiquetas de Índice o Columnas en un DataFrame 🏷️
- El método `rename` acepta un diccionario para sus parámetros `columns` o `index`.
  - Las claves del diccionario representan los nombres existentes.
  - Los valores representan los nuevos nombres.
- También es posible sobrescribir directamente el atributo `columns` del **DataFrame**.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

ValueError: Index Film invalid

In [ ]:
bond = bond.rename(columns={ "Year": "Year of Release", "Box Office": "Revenue" })
bond.head()

,Year of Release,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
#Cambio de valores en el indice
swaps = {
    "Dr. No": "Dr No",
    "GoldenEye": "Golden Eye",
    "The World Is Not Enough": "Best Bond Movie Ever"
}

bond = bond.rename(index=swaps)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,200.0
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Double Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr No,1962,Double Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Double Sir Sean Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Double Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Double Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Best Bond Movie Ever,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Double Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Double Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [ ]:
bond.columns

Index(['Year', 'Bond Guy', 'Camera Dude', 'Revenues', 'Cost', 'Salary'], dtype='object')

In [ ]:
bond.columns = ["Year", "Bond Guy", "Camera Dude", "Revenues", "Cost", "Salary"] #Cambimos los nombres de la columna con una lista

In [ ]:
bond

,Year,Bond Guy,Camera Dude,Revenues,Cost,Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,200.0
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Double Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr No,1962,Double Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Double Sir Sean Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Double Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Double Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Best Bond Movie Ever,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Double Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Double Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [ ]:
# bond.columns[3] = "The Money"

## Eliminar Filas o Columnas de un DataFrame 🗑️
- El método `drop` elimina una o más filas/columnas de un **DataFrame**.
- Pasa una lista al parámetro `index` o `columns` para especificar qué eliminar.
- El método `pop` elimina y devuelve una **Serie** (y modifica el **DataFrame** en el proceso).
- La palabra clave `del` en Python también elimina una única **Serie**.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film", sep = ";").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
bond.drop(columns = ["Box Office", "Budget","Actor","Year"])

                                           Director  Bond Actor Salary
Film
A View to a Kill                          John Glen                9.1
Casino Royale                       Martin Campbell                3.3
Casino Royale                            Ken Hughes                NaN
Diamonds Are Forever                   Guy Hamilton                5.8
Die Another Day                        Lee Tamahori               17.9
Dr. No                                Terence Young                0.6
For Your Eyes Only                        John Glen                NaN
From Russia with Love                 Terence Young                1.6
GoldenEye                           Martin Campbell                5.1
Goldfinger                             Guy Hamilton                3.2
Licence to Kill                           John Glen                7.9
Live and Let Die                       Guy Hamilton                NaN
Moonraker                             Lewis Gilbert                NaN
Never Say Never Again                Irvin Kershner                NaN
No Time to Die                   Cary Joji Fukunaga               25.0
Octopussy                                 John Glen                7.8
On Her Majesty's Secret Service       Peter R. Hunt                0.6
Quantum of Solace                      Marc Forster                8.1
Skyfall                                  Sam Mendes               14.5
Spectre                                  Sam Mendes               30.0
The Living Daylights                      John Glen                5.2
The Man with the Golden Gun            Guy Hamilton                NaN
The Spy Who Loved Me                  Lewis Gilbert                NaN
The World Is Not Enough               Michael Apted               13.5
Thunderball                           Terence Young                4.7
Tomorrow Never Dies              Roger Spottiswoode               10.0
You Only Live Twice                   Lewis Gilbert                4.4

In [ ]:
bond.drop(columns = ["Box Office", "Budget"])
bond.drop(index=["No Time to Die", "Casino Royale"])
bond.drop(index=["No Time to Die", "Casino Royale"], columns=["Box Office", "Budget"])

,Year,Actor,Director,Bond Actor Salary
Film,,,,
A View to a Kill,1985,Roger Moore,John Glen,9.1
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,17.9
Dr. No,1962,Sean Connery,Terence Young,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,NaN
From Russia with Love,1963,Sean Connery,Terence Young,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,NaN
Octopussy,1983,Roger Moore,John Glen,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,14.5
Spectre,2015,Daniel Craig,Sam Mendes,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,13.5
Thunderball,1965,Sean Connery,Terence Young,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,4.4

In [ ]:
lista = [1,2,3,4,5]
lista.pop()
actor = bond.pop("Actor") #Esto devuelve una serie con lo que se borro
actor.head()

Film
A View to a Kill           Roger Moore
Casino Royale             Daniel Craig
Casino Royale              David Niven
Diamonds Are Forever      Sean Connery
Die Another Day         Pierce Brosnan
Name: Actor, dtype: object

In [ ]:
del bond["Year"]

In [ ]:
del bond["Director"]

In [ ]:
bond.head()

                      Box Office  Budget  Bond Actor Salary
Film
A View to a Kill           275.2    54.5                9.1
Casino Royale              581.5   145.3                3.3
Casino Royale              315.0    85.0                NaN
Diamonds Are Forever       442.5    34.7                5.8
Die Another Day            465.4   154.2               17.9

## Crear una Muestra Aleatoria con el Método `sample` 🎲
- El método `sample` devuelve una o más filas aleatorias del **DataFrame**.
- Personaliza el parámetro `axis` para extraer columnas aleatorias.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film", sep = ";").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
bond.sample(n = 2, axis = "columns")

                                 Budget            Director
Film
A View to a Kill                   54.5           John Glen
Casino Royale                     145.3     Martin Campbell
Casino Royale                      85.0          Ken Hughes
Diamonds Are Forever               34.7        Guy Hamilton
Die Another Day                   154.2        Lee Tamahori
Dr. No                              7.0       Terence Young
For Your Eyes Only                 60.2           John Glen
From Russia with Love              12.6       Terence Young
GoldenEye                          76.9     Martin Campbell
Goldfinger                         18.6        Guy Hamilton
Licence to Kill                    56.7           John Glen
Live and Let Die                   30.8        Guy Hamilton
Moonraker                          91.5       Lewis Gilbert
Never Say Never Again              86.0      Irvin Kershner
No Time to Die                    301.0  Cary Joji Fukunaga
Octopussy                          53.9           John Glen
On Her Majesty's Secret Service    37.3       Peter R. Hunt
Quantum of Solace                 181.4        Marc Forster
Skyfall                           170.2          Sam Mendes
Spectre                           206.3          Sam Mendes
The Living Daylights               68.8           John Glen
The Man with the Golden Gun        27.7        Guy Hamilton
The Spy Who Loved Me               45.1       Lewis Gilbert
The World Is Not Enough           158.3       Michael Apted
Thunderball                        41.9       Terence Young
Tomorrow Never Dies               133.9  Roger Spottiswoode
You Only Live Twice                59.9       Lewis Gilbert

In [ ]:
bond.sample()
bond.sample(n=5)
bond.sample(n=3, axis="rows")
bond.sample(n=2, axis="columns")

                                           Director  Year
Film
A View to a Kill                          John Glen  1985
Casino Royale                       Martin Campbell  2006
Casino Royale                            Ken Hughes  1967
Diamonds Are Forever                   Guy Hamilton  1971
Die Another Day                        Lee Tamahori  2002
Dr. No                                Terence Young  1962
For Your Eyes Only                        John Glen  1981
From Russia with Love                 Terence Young  1963
GoldenEye                           Martin Campbell  1995
Goldfinger                             Guy Hamilton  1964
Licence to Kill                           John Glen  1989
Live and Let Die                       Guy Hamilton  1973
Moonraker                             Lewis Gilbert  1979
Never Say Never Again                Irvin Kershner  1983
No Time to Die                   Cary Joji Fukunaga  2021
Octopussy                                 John Glen  1983
On Her Majesty's Secret Service       Peter R. Hunt  1969
Quantum of Solace                      Marc Forster  2008
Skyfall                                  Sam Mendes  2012
Spectre                                  Sam Mendes  2015
The Living Daylights                      John Glen  1987
The Man with the Golden Gun            Guy Hamilton  1974
The Spy Who Loved Me                  Lewis Gilbert  1977
The World Is Not Enough               Michael Apted  1999
Thunderball                           Terence Young  1965
Tomorrow Never Dies              Roger Spottiswoode  1997
You Only Live Twice                   Lewis Gilbert  1967

## Métodos `nsmallest` y `nlargest` 🔝🔽
- El método `nlargest` devuelve un número especificado de filas con los valores más grandes de una columna.
- El método `nsmallest` devuelve filas con los valores más pequeños de una columna.
- Ambos métodos son más eficientes que ordenar todo el **DataFrame**.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film", sep = ";").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
bond.sort_values("Box Office", ascending=False)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [ ]:
top_5_peliculas_que_mas_ganaron = bond.nlargest(n = 5, columns="Box Office")

In [ ]:
top_5_peliculas_que_mas_ganaron

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1

In [ ]:
bond.nlargest(n=4, columns="Box Office")
bond["Box Office"].nlargest(4)

Film
Skyfall           943.5
Thunderball       848.1
Goldfinger        820.4
No Time to Die    774.2
Name: Box Office, dtype: float64

In [ ]:
bond.nsmallest(3, columns="Bond Actor Salary")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [ ]:
bond["Bond Actor Salary"].nsmallest(3)

Film
Dr. No                             0.6
On Her Majesty's Secret Service    0.6
From Russia with Love              1.6
Name: Bond Actor Salary, dtype: float64

In [ ]:
bond.nsmallest(3, columns="Bond Actor Salary")
bond["Bond Actor Salary"].nsmallest(3)

Film
Dr. No                             0.6
On Her Majesty's Secret Service    0.6
From Russia with Love              1.6
Name: Bond Actor Salary, dtype: float64

## Filtrar con el Método `where` 🔍
- Similar a los corchetes o `loc`, el método `where` filtra un **DataFrame** usando una **Series** booleana.
- Las filas que no cumplan con los criterios se rellenan con valores `NaN`.
- Mantener los valores `NaN` puede ser útil para ciertas operaciones de combinación y visualización.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
actor_is_sean_connery = bond["Actor"] == "Sean Connery"
actor_is_sean_connery

Film
A View to a Kill                   False
Casino Royale                      False
Casino Royale                      False
Diamonds Are Forever                True
Die Another Day                    False
Dr. No                              True
For Your Eyes Only                 False
From Russia with Love               True
GoldenEye                          False
Goldfinger                          True
Licence to Kill                    False
Live and Let Die                   False
Moonraker                          False
Never Say Never Again               True
No Time to Die                     False
Octopussy                          False
On Her Majesty's Secret Service    False
Quantum of Solace                  False
Skyfall                            False
Spectre                            False
The Living Daylights               False
The Man with the Golden Gun        False
The Spy Who Loved Me               False
The World Is Not Enough            False
Thunderball                         True
Tomorrow Never Dies                False
You Only Live Twice                 True
Name: Actor, dtype: bool

In [ ]:
actor_is_sean_connery = bond["Actor"] == "Sean Connery"
bond[actor_is_sean_connery]
bond.loc[actor_is_sean_connery]
bond.where(actor_is_sean_connery) # Si no cumple la condicion devuelve NaN / Nulo

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## El Método `apply` con DataFrames 🛠️
- El método `apply` invoca una función en cada columna o fila del **DataFrame**.
- Pasa la función sin invocar como primer argumento.
- Usa el parámetro `axis` con el valor `"columns"` para aplicar la función a cada fila.
- Pandas pasará los valores de la fila como una **Series**, permitiendo el uso de accesorios como `loc` e `iloc`.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film", sep = ";").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
bond["Actor"].apply(len)

Film
A View to a Kill                   11
Casino Royale                      12
Casino Royale                      11
Diamonds Are Forever               12
Die Another Day                    14
Dr. No                             12
For Your Eyes Only                 11
From Russia with Love              12
GoldenEye                          14
Goldfinger                         12
Licence to Kill                    14
Live and Let Die                   11
Moonraker                          11
Never Say Never Again              12
No Time to Die                     12
Octopussy                          11
On Her Majesty's Secret Service    14
Quantum of Solace                  12
Skyfall                            12
Spectre                            12
The Living Daylights               14
The Man with the Golden Gun        11
The Spy Who Loved Me               11
The World Is Not Enough            14
Thunderball                        12
Tomorrow Never Dies                14
You Only Live Twice                12
Name: Actor, dtype: int64

In [ ]:
bond.head(1)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [ ]:
bond.head(10)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [ ]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [ ]:
year = bond.loc["Year"]
year

KeyError: 'Year'

In [ ]:
# Ejemplo de funcion

def rank_movie(row):
    year = row.loc["Year"]
    actor = row.loc["Actor"]
    budget = row.loc["Budget"]

    if year >= 1980 and year < 1990:
        return "Great 80's"

    if actor == "Pierce Brosnan":
        return "The best Bond ever!"

    if budget > 100:
        return "Expensive movie"

    return "No comment"

bond["rank_movie"] = bond.apply(rank_movie, axis = "columns")

In [ ]:

def budget_check(row):
    budget = row.loc["Budget"]

    if budget > 100:
        return "Expensive movie"

    if budget < 100:
        return "Normal"
    return "No comment"

bond["budget_flag"] = bond.apply(budget_check, axis = "columns")

In [ ]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary,rank_movie,budget_flag
Film,,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1,Great 80's,Normal
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3,Expensive movie,Expensive movie
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,No comment,Normal
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8,No comment,Normal
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9,The best Bond ever!,Expensive movie
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6,No comment,Normal
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN,Great 80's,Normal
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6,No comment,Normal
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1,The best Bond ever!,Normal
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2,No comment,Normal
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9,Great 80's,Normal
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN,No comment,Normal
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN,No comment,Normal
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN,Great 80's,Normal
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0,Expensive movie,Expensive movie
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8,Great 80's,Normal
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6,No comment,Normal
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1,Expensive movie,Expensive movie
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5,Expensive movie,Expensive movie
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0,Expensive movie,Expensive movie
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2,Great 80's,Normal
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN,No comment,Normal
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN,No comment,Normal
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5,The best Bond ever!,Expensive movie
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7,No comment,Normal
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0,The best Bond ever!,Expensive movie
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4,No comment,Normal