
# Trabajo con Datos de Texto 📝

In [ ]:
import pandas as pd

## Conjunto de Datos de Este Módulo 📂
- El conjunto de datos de este módulo (`chicago.csv`) es una colección de empleados del sector público de la ciudad de Chicago.
- Cada fila incluye el nombre del empleado, su cargo, departamento y salario.

In [ ]:
chicago = pd.read_csv("chicago.csv", sep = ";")
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
chicago.columns

Index(['Name', 'Position Title', 'Department', 'Employee Annual Salary'], dtype='object')

In [ ]:
chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  object
dtypes: object(4)
memory usage: 1002.1+ KB

In [ ]:
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
chicago.tail()

,Name,Position Title,Department,Employee Annual Salary
32057,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00

In [ ]:
chicago.nunique()

Name                      31776
Position Title             1093
Department                   35
Employee Annual Salary     1156
dtype: int64

In [ ]:
chicago["Department"] = chicago["Department"].astype("category")

In [ ]:
chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  category
 3   Employee Annual Salary  32062 non-null  object
dtypes: category(1), object(3)
memory usage: 784.2+ KB

In [ ]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
chicago["Salary"] = chicago["Salary"].astype(float)

KeyError: 'Salary'

## Métodos Comunes de Cadenas en Series 🔡
- Una **Series** tiene un atributo especial `str` que expone un objeto con métodos de cadenas.
- Accede al atributo `str` y luego invoca el método de cadena en el objeto anidado.
- La mayoría de los nombres de los métodos coinciden con sus equivalentes en Python (`upper`, `lower`, `title`, etc.).

In [ ]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
chicago["Position Title"].str.strip() #Elimina los espacios del principio y del final

0            ELVIA J
1          JEFFERY M
2             KARINA
3        KIMBERLEI R
4          VICENTE M
            ...
32057      MICHAEL J
32058        PETER J
32059         MARK E
32060        CARLO E
32061        DARIUSZ
Name: Position Title, Length: 32062, dtype: object

In [ ]:
chicago["Position Title"].str.title().str.len()

0        16
1        14
2        14
3        24
4        17
         ..
32057    30
32058    14
32059    14
32060    14
32061    23
Name: Position Title, Length: 32062, dtype: int64

In [ ]:
chicago["Position Title"].str.lower()
chicago["Position Title"].str.upper()
chicago["Position Title"].str.title()
chicago["Position Title"].str.len()
chicago["Position Title"].str.title().str.len()
chicago["Position Title"].str.strip() #Borra el espacio del inicio y del final si existe
chicago["Position Title"].str.lstrip() #Borra el espacio del inicio (LEFT)
chicago["Position Title"].str.rstrip() #Borra el espacio del inicio (RIGHT)

0        Water Management
1                  Police
2                  Police
3        General Services
4        Water Management
               ...
32057    General Services
32058              Police
32059              Police
32060              Police
32061                Doit
Name: Department, Length: 32062, dtype: object

In [ ]:

chicago["Department"].str.replace("POLICE", "policia").str.title().str.strip()

0                      Water Rate Taker
1                       Policia Officer
2                       Policia Officer
3              Chief Contract Expediter
4                     Civil Engineer Iv
                      ...
32057    Frm Of Machinists - Automotive
32058                   Policia Officer
32059                   Policia Officer
32060                   Policia Officer
32061           Chief Data Base Analyst
Name: Department, Length: 32062, dtype: object

## Filtrado con Métodos de Cadenas 🔍
- El método `str.contains` verifica si una subcadena existe en cualquier parte de la cadena.
- El método `str.startswith` verifica si una subcadena existe al inicio de la cadena.
- El método `str.endswith` verifica si una subcadena existe al final de la cadena.

In [ ]:
chicago = pd.read_csv("chicago.csv",sep = ";").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
water_workers = chicago["Position Title"].str.lower().str.contains("water")
chicago[water_workers]

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
554,"ALUISE, VINCENT G",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
685,"ANDERSON, ANDREW J",DISTRICT SUPERINTENDENT OF WATER DISTRIBUTION,WATER MGMNT,$109272.00
702,"ANDERSON, DONALD",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
...,...,...,...,...
29669,"VERMA, ANUPAM",MANAGING ENGINEER - WATER MANAGEMENT,WATER MGMNT,$111192.00
30239,"WASHINGTON, JOSEPH",WATER CHEMIST III,WATER MGMNT,$89676.00
30544,"WEST, THOMAS R",GEN SUPT OF WATER MANAGEMENT,WATER MGMNT,$115704.00
30991,"WILLIAMS, MATTHEW",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
31405,"WOODRIDGE, ROBERT L",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00

In [ ]:
starts_with_pesos = chicago["Employee Annual Salary"].str.startswith("$") #Filtro booleano

In [ ]:
chicago.shape

(32062, 4)

In [ ]:
chicago[starts_with_pesos].shape #Revisamos que todos los registros de salary tienen el signo $

(32062, 4)

In [ ]:
starts_with_civil = chicago["Department"].str.lower().str.startswith("civil")

In [ ]:
starts_with_civil

0        False
1        False
2        False
3        False
4         True
         ...
32057    False
32058    False
32059    False
32060    False
32061    False
Name: Department, Length: 32062, dtype: bool

In [ ]:
chicago[starts_with_civil]

,Name,Position Title,Department,Employee Annual,Salary
4,ABAD JR,VICENTE M,CIVIL ENGINEER IV,WATER MGMNT,$106836.00
25,ABDULSATTAR,MUDHAR,CIVIL ENGINEER II,WATER MGMNT,$58536.00
34,ABRAHAM,GIRLEY T,CIVIL ENGINEER IV,WATER MGMNT,$106836.00
55,ABUTALEB,AHMAD H,CIVIL ENGINEER II,WATER MGMNT,$89676.00
147,ADAMS,TANERA C,CIVIL ENGINEER IV,TRANSPORTN,$106836.00
...,...,...,...,...,...
31623,YANG,LUYANG,CIVIL ENGINEER V,TRANSPORTN,$116784.00
31656,YEPEZ,JESUS,CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31662,YESUFU,STEPHANIE A,CIVIL ENGINEER III,TRANSPORTN,$92784.00
31797,ZAKE,JOSHUA S,CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31935,ZHANG,ANNE,CIVIL ENGINEER III,TRANSPORTN,$77364.00

In [ ]:
starts_with_civil = chicago["Position Title"].str.lower().str.startswith("civil")
chicago.loc[starts_with_civil]

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
25,"ABDULSATTAR, MUDHAR",CIVIL ENGINEER II,WATER MGMNT,$58536.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
55,"ABUTALEB, AHMAD H",CIVIL ENGINEER II,WATER MGMNT,$89676.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
...,...,...,...,...
31623,"YANG, LUYANG",CIVIL ENGINEER V,TRANSPORTN,$116784.00
31656,"YEPEZ, JESUS",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31662,"YESUFU, STEPHANIE A",CIVIL ENGINEER III,TRANSPORTN,$92784.00
31797,"ZAKE, JOSHUA S",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31935,"ZHANG, ANNE",CIVIL ENGINEER III,TRANSPORTN,$77364.00

In [ ]:
ends_with_iv = chicago["Position Title"].str.lower().str.endswith("iv")
chicago[ends_with_iv]

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
145,"ADAMS, SHERYLL A",LIBRARIAN IV,PUBLIC LIBRARY,$97812.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
166,"ADENI, MOHAMED K",ACCOUNTANT IV,FINANCE,$97812.00
...,...,...,...,...
31777,"ZAFIRIS, CHRISTOPHER",ARCHITECT IV,DISABILITIES,$106836.00
31797,"ZAKE, JOSHUA S",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31870,"ZAVALA, FERNANDO",ACCOUNTANT IV,FINANCE,$97812.00
31884,"ZAWADSKI, JAMES",CLERK IV,LAW,$68028.00
32008,"ZOTTA, SANDINO",MECHANICAL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
ends_with_fernando = chicago["Position Title"].str.lower().str.endswith("fernando")
chicago[ends_with_fernando]

,Name,Position Title,Department,Employee Annual,Salary
1378,BANDA,FERNANDO,POLICE OFFICER,POLICE,$87384.00
4041,CARRETO JR,FERNANDO,POLICE OFFICER,POLICE,$81588.00
4184,CARVAJAL,FERNANDO,POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,$98016.00
4272,CASTILLA,FERNANDO,CIVIL ENGINEER IV,TRANSPORTN,$106836.00
6681,DELGADILLO,FERNANDO,PARAMEDIC,FIRE,$70380.00
6912,DIAZ,FERNANDO,FIREFIGHTER-EMT,FIRE,$89568.00
8099,ESPINOZA,FERNANDO,CITY PLANNER V,COMMUNITY DEVELOPMENT,$84996.00
8763,FLORES,FERNANDO,POLICE OFFICER,POLICE,$90618.00
8782,FLORES JR,FERNANDO,CONSTRUCTION LABORER,WATER MGMNT,$81536.00
9436,GALVEZ,FERNANDO,LIBRARY ASSOCIATE,PUBLIC LIBRARY,$43776.00
18733,MENDEZ,FERNANDO,FIREFIGHTER-EMT (RECRUIT),FIRE,$66606.00
19273,MOCTEZUMA,FERNANDO,POLICE OFFICER,POLICE,$74028.00
21171,OLVERA JR,FERNANDO,POLICE OFFICER,POLICE,$70380.00
24337,ROCHA,FERNANDO,MACHINIST (AUTOMOTIVE),GENERAL SERVICES,$94328.00
24437,RODRIGUEZ,FERNANDO,POLICE OFFICER,POLICE,$81588.00
24690,ROMERO,FERNANDO,POLICE OFFICER,POLICE,$46668.00
27135,SOTO,FERNANDO,POLICE OFFICER,POLICE,$81588.00
31870,ZAVALA,FERNANDO,ACCOUNTANT IV,FINANCE,$97812.00

## Métodos de Cadenas en Índices y Columnas 🏷️
- Usa los atributos `index` y `columns` para acceder a las etiquetas de índice y columnas del **DataFrame**.
- Estos objetos soportan métodos de cadenas a través de su propio atributo `str`.

In [ ]:
chicago = pd.read_csv("chicago.csv", index_col="Name", sep= ";").dropna(how="all").sort_index() #Leo chicago, elijo como indice Name, borro los N/A y ordeno asc
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
chicago.index = chicago.index.str.strip().str.title()

In [ ]:
chicago

,Position Title,Department,Employee Annual Salary
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...
"Zygadlo, Michael J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
"Zygowicz, Peter J",POLICE OFFICER,POLICE,$87384.00
"Zymantas, Mark E",POLICE OFFICER,POLICE,$84450.00
"Zyrkowski, Carlo E",POLICE OFFICER,POLICE,$87384.00
"Zyskowski, Dariusz",CHIEF DATA BASE ANALYST,DoIT,$113664.00

In [ ]:
chicago.columns = chicago.columns.str.title()

In [ ]:
chicago

,Position Title,Department,Employee Annual Salary
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...
"Zygadlo, Michael J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
"Zygowicz, Peter J",POLICE OFFICER,POLICE,$87384.00
"Zymantas, Mark E",POLICE OFFICER,POLICE,$84450.00
"Zyrkowski, Carlo E",POLICE OFFICER,POLICE,$87384.00
"Zyskowski, Dariusz",CHIEF DATA BASE ANALYST,DoIT,$113664.00

In [ ]:
chicago.head()

        Position Title                Department  Employee Annual       Salary
Name
Aaron          ELVIA J          WATER RATE TAKER       WATER MGMNT   $90744.00
Aaron        JEFFERY M            POLICE OFFICER            POLICE   $84450.00
Aaron           KARINA            POLICE OFFICER            POLICE   $84450.00
Aaron      KIMBERLEI R  CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   $89880.00
Abad Jr      VICENTE M         CIVIL ENGINEER IV       WATER MGMNT  $106836.00

## El Método `split` ✂️
- El método `str.split` divide una cadena según la aparición de un delimitador. Pandas devuelve una **Series** de listas.
- Usa el método `str.get` para acceder a un elemento de la lista anidada por su posición de índice.

In [ ]:
chicago = pd.read_csv("chicago.csv", sep = ";").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
chicago = pd.read_csv("chicago.csv",sep=";").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

,Name,Position Title,Department,Employee Annual,Salary
0,AARON,ELVIA J,WATER RATE TAKER,WATER MGMNT,$90744.00
1,AARON,JEFFERY M,POLICE OFFICER,POLICE,$84450.00
2,AARON,KARINA,POLICE OFFICER,POLICE,$84450.00
3,AARON,KIMBERLEI R,CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,ABAD JR,VICENTE M,CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
chicago["Department"].str.split(" ")

0             [WATER, MGMNT]
1                   [POLICE]
2                   [POLICE]
3        [GENERAL, SERVICES]
4             [WATER, MGMNT]
                ...
32057    [GENERAL, SERVICES]
32058               [POLICE]
32059               [POLICE]
32060               [POLICE]
32061                 [DoIT]
Name: Department, Length: 32062, dtype: object

In [ ]:
# The most common first word in our job positions/titles
chicago["Position Title"].str.split(" ").str.get(0).value_counts()

Position Title
POLICE             10856
FIREFIGHTER-EMT     1509
SERGEANT            1186
POOL                 918
FIREFIGHTER          810
                   ...
PORTFOLIO              1
SUPERVISOR             1
SUPT                   1
STRUCTURAL             1
CORPORATION            1
Name: count, Length: 320, dtype: int64

## Más Práctica con `split` 🧩

In [ ]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
# Finding the most common first name among the employees

chicago["Name"].str.title().str.split(", ").str.get(1).str.strip().str.split(" ").str.get(0).value_counts()

Name
Michael     1153
John         899
James        676
Robert       622
Joseph       537
            ...
Deena          1
Cherrise       1
Eartha         1
Ernika         1
Mac            1
Name: count, Length: 5091, dtype: int64

## Parámetros `expand` y `n` del Método `split` ⚙️
- El parámetro `expand` devuelve un **DataFrame** en lugar de una **Series** de listas.
- El parámetro `n` limita el número de divisiones realizadas.

In [ ]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
chicago[["Last Name", "First Name"]] = chicago["Name"].str.split(",", expand=True)

In [ ]:
chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Last Name,First Name
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,AARON,ELVIA J
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,AARON,JEFFERY M
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,AARON,KARINA
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,AARON,KIMBERLEI R
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,ABAD JR,VICENTE M

In [ ]:
chicago[["Primary Title", "Secondary Title"]] = chicago["Position Title"].str.split(" ", expand=True, n=1)

In [ ]:
chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Last Name,First Name,Primary Title,Secondary Title
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,AARON,ELVIA J,WATER,RATE TAKER
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,AARON,JEFFERY M,POLICE,OFFICER
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,AARON,KARINA,POLICE,OFFICER
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,AARON,KIMBERLEI R,CHIEF,CONTRACT EXPEDITER
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,ABAD JR,VICENTE M,CIVIL,ENGINEER IV

## El Método `extract` 🎯
- El método `str.extract` utiliza expresiones regulares para extraer patrones de cadenas.
- Es útil para extraer información específica y estructurada de texto no estructurado.
- Puede extraer múltiples grupos de una expresión regular en columnas separadas de un **DataFrame**.

In [ ]:
data = {"columna_texto": ["ID: 123, Nombre: Juan", "ID: 456, Nombre: Maria", "ID: 789, Nombre: Pedro"]}
df_ejemplo = pd.DataFrame(data)

# Definir un patrón de expresión regular para extraer el ID y el Nombre
# r"..." indica una cadena sin procesar (raw string)
# (...) crea un grupo de captura para extraer una parte de la cadena
# ID:\s* Coincide con "ID:" seguido de cero o más espacios en blanco
# (\d+) Captura uno o más dígitos (el ID)
# ,\s* Coincide con una coma seguida de cero o más espacios en blanco
# Nombre:\s* Coincide con "Nombre:" seguido de cero o más espacios en blanco
# ([\w\s]+) Captura uno o más caracteres alfanuméricos o espacios en blanco (el Nombre)
pattern_simple = r"ID:\s*(\d+),\s*Nombre:\s*([\w\s]+)"

# Usar str.extract() para extraer el ID y el Nombre en nuevas columnas
# El método extract() devuelve un DataFrame con las partes capturadas
df_extraido = df_ejemplo["columna_texto"].str.extract(pattern_simple)

# Mostrar el DataFrame original y el DataFrame con los datos extraídos
print("DataFrame original:")
display(df_ejemplo)

print("\nDataFrame con datos extraídos:")
display(df_extraido)

DataFrame original:

            columna_texto
0   ID: 123, Nombre: Juan
1  ID: 456, Nombre: Maria
2  ID: 789, Nombre: Pedro

DataFrame con datos extraídos:

     0      1
0  123   Juan
1  456  Maria
2  789  Pedro